### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by gajus** [krasimir/babel-plugin-transform-cssx#1]
This code base looks abandoned. Instead, you have released a [bunch of loaders](https://github.com/krasimir/cssx/tree/master/packages). However, unless there is a Babel transpilar, using CSSX in a universal app is going to be a hacky business.

**Comment by krasimir** [comment]
Actually the whole idea of creating a babel plugin is bad because Babel's babylon does not accept plugins. I opened a [PR](https://github.com/babel/babylon/pull/11) about that but it was rejected. So, under the hood, [CSSX transpiler](https://github.com/krasimir/cssx/tree/master/packages/cssx-transpiler) still [uses](https://github.com/krasimir/cssx/tree/master/packages/cssx-transpiler/src/vendor) babylon but it wasn't possible to make it part of babel.

If you plan using cssx along with babel just make sure that cssx transpiler is called before babel. Otherwise babel will flag the code as invalid.

**Comment by gajus** [comment]
That'd mean that I would need to run two services to transpile my code. babel watch and cssx watch. If you are using a bundler such as webpack or a task runner such as gulp, that's not going to be much of a problem, but it is a complete bummer for vanilla guys.

But I get it – Babel doesn't support plugins.

**Comment by krasimir** [comment]
> If you are using a bundler such as webpack or a task runner such as gulp, that's not going to be much of a problem, but it is a complete bummer for vanilla guys.

I agree. I tried integrating CSSX syntax in babel but there are some considerations and my proposal wasn't accepted.
